import { formatDuration } from "../../../packages/tracking-engine/timeline.js";
const $=selector=>document.querySelector(selector); const period=$("#period"), from=$("#from"), to=$("#to"), status=$("#status"), content=$("#content");
function dateText(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function dayStart(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime()}
function range(){const now=new Date(), end=dayStart(new Date(now.getFullYear(),now.getMonth(),now.getDate()+1));if(period.value==="today")return{from:dayStart(now),to:end};if(period.value==="yesterday")return{from:dayStart(new Date(now.getFullYear(),now.getMonth(),now.getDate()-1)),to:dayStart(now)};if(period.value==="week")return{from:dayStart(new Date(now.getFullYear(),now.getMonth(),now.getDate()-6)),to:end};if(period.value==="month")return{from:dayStart(new Date(now.getFullYear(),now.getMonth(),now.getDate()-29)),to:end};return{from:dayStart(new Date(`${from.value}T00:00:00`)),to:dayStart(new Date(`${to.value}T00:00:00`))+86400000}}
function send(message){return chrome.runtime.sendMessage(message).then(r=>{if(!r?.ok)throw new Error(r?.error||"Request failed");return r.data})}
function bars(target,items,maxItems=6){const node=$(target);node.replaceChildren();const shown=items.slice(0,maxItems),max=Math.max(1,...shown.map(x=>x.seconds));for(const item of shown){const row=document.createElement("div");row.className="bar-row";const name=document.createElement("span"),bar=document.createElement("div"),fill=document.createElement("i"),value=document.createElement("strong");name.textContent=item.name;bar.className="bar";fill.style.width=`${100*item.seconds/max}%`;bar.append(fill);value.textContent=formatDuration(item.seconds);row.append(name,bar,value);node.append(row)}}
function render(data){$("#active").textContent=formatDuration(data.totals.active);$("#productive").textContent=formatDuration(data.totals.productive);$("#neutral").textContent=formatDuration(data.totals.neutral);$("#distracted").textContent=formatDuration(data.totals.distracted);$("#switches").textContent=data.tabSwitches;$("#score").textContent=data.focus.score;const factors=$("#factors");factors.replaceChildren();for(const f of data.focus.factors){const row=document.createElement("div");row.className="factor";const label=document.createElement("span"),value=document.createElement("strong"),track=document.createElement("div"),fill=document.createElement("i");label.textContent=f.label;value.textContent=`${f.points}/${f.maximum}`;track.className="track";fill.className="fill";fill.style.width=`${100*f.points/f.maximum}%`;track.append(fill);row.append(label,value,track);factors.append(row)}bars("#balance",[{name:"Productive",seconds:data.totals.productive},{name:"Neutral",seconds:data.totals.neutral},{name:"Distracted",seconds:data.totals.distracted}],3);bars("#categories",data.byCategory);bars("#domains",data.byDomain);const map=Object.fromEntries(data.byHour.map(x=>[x.name,x.seconds])),hours=$("#hours");hours.replaceChildren();const max=Math.max(1,...Object.values(map));for(let h=0;h<24;h++){const item=document.createElement("div"),bar=document.createElement("i"),label=document.createElement("span"),key=String(h).padStart(2,"0");item.className="hour";bar.style.height=`${100*(map[key]||0)/max}%`;bar.title=formatDuration(map[key]||0);label.textContent=h%3===0?key:"";item.append(bar,label);hours.append(item)}status.hidden=true;content.hidden=false}
async function load(){status.hidden=false;content.hidden=true;status.textContent="Loading analytics…";try{const data=await send({type:"analytics:summary",range:range()});if(!data.totals.active){status.textContent="No tracked activity in this period yet.";return}render(data)}catch(e){status.textContent=`Could not load analytics: ${e.message}`}}
period.addEventListener("change",()=>{const custom=period.value==="custom";from.hidden=to.hidden=!custom;if(custom){const d=new Date();from.value=to.value=dateText(d)}load()});from.addEventListener("change",load);to.addEventListener("change",load);load();
